### ISSUE TITLE
Is documentation page dead?

### ISSUE THREAD

**Issue by itsmeurbi** [mbraak/jqTree#749]
Readme file references a Github Page for documentation multiple times but it looks like it's dead now
I'm visiting:
http://mbraak.github.io/jqTree as mentioned [here](https://github.com/mbraak/jqTree#documentation)

<img width="1337" alt="Screen Shot 2023-09-17 at 14 17 40" src="https://github.com/mbraak/jqTree/assets/26292224/91781ec1-248d-4843-a06b-cad30a0ade86">

**Comment by mbraak** [comment]
I'll have a look

**Comment by mbraak** [comment]
Fixed

**Comment by itsmeurbi** [comment]
Interesting, @mbraak I'm still getting the 404 error
<img width="1337" alt="Screen Shot 2023-09-19 at 9 46 37" src="https://github.com/mbraak/jqTree/assets/26292224/a249b9fd-3e06-4a06-9e21-33afc154cbc1">

**Comment by mbraak** [comment]
I deployed the site again. I'll try to find out why the site keeps disappearing.
